spring:
  datasource:
    url: ENC(dfXlO3g3m4mpQSftAMkBYZwIy/pv5NzKRaJ8QgkhghxSRDVPuP3SDksF1hC/x0BnT8eYDxSvIJ4=)
    username: ENC(xm788MHwRupSZB0VSe7H5w==)
    password: ENC(u2CtGfVBCg9pkHG6pmAe1w==)
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(QqHZftr0SvBFUfwErzRg4LWtQZXLy4l+Gx+HVHTqRdo=)
    password: ENC(CahuRyBTeu0XqoM3BLwytRo2FQraKWFHxs9MPbWpmAU=)
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

  #  thymeleaf:
  #    prefix: classpath:/templates/
  #    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update    # ???? table? ????
    properties:
      hibernate:
        #show_sql: true    # ?????? ???? ???, logger? ?? ?? (system.out?? ???)
        #format_sql: true

logging.level:
  org.hibernate.SQL: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
