server:
  port: 9097

spring:
  profiles:
    active: local
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    generate-ddl: true
    database: default
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(S1dMTDGHPST3LDR4HOxwoNEFHMBZcX1ZVwgpLj3Jnp9EvoloKX0SqB0qLeWb/6Ga)
            client-secret: ENC(FgLNufarvhL5JDcViV+tRogLjqZaz1JHEDJt3tHd9UIbyg053g7jtkntwb0igVAx)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email #동의 항목
            client-name: Kakao
          naver:
            client-id: ENC(SiBXV66ixOgvP5Yqg8IQ0NuMjy0z1MTi94lLWtB9t/c=)
            client-secret: ENC(eBH+5rK++38sv0MLo8UnEDb7YwC356YL)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
          google:
            client-id: ENC(PvCEupLaywZ7m1v3qQ1qkGJo58+xl5RqrAaIfm3Ii5w8uqTS8rl5qddcthIBonXtU1KgGBaDG8QSy6GLqBCYWYk6AEeBXkMC4LtAqe8aAyq4jSYvzF/PFw==)
            client-secret: ENC(h3Rbsl4cfBawYuADZYO4wkHVRMZ/Y/LD2wEn6KhWJsfiz3lKePqLXnuJB5+GUeM8)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: email, profile
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
# logging:
  #   level:
  #     org:
  #       springframework:
  #         security:
  #           web: trace
  #     com:
  #       crow: debug