server:
  port: 9097

spring:
  profiles:
    active: local
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    generate-ddl: true
    database: default
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(S1dMTDGHPST3LDR4HOxwoNEFHMBZcX1ZVwgpLj3Jnp9EvoloKX0SqB0qLeWb/6Ga)
            client-secret: ENC(FgLNufarvhL5JDcViV+tRogLjqZaz1JHEDJt3tHd9UIbyg053g7jtkntwb0igVAx)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email #동의 항목
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
# logging:
  #   level:
  #     org:
  #       springframework:
  #         security:
  #           web: trace
  #     com:
  #       crow: debug